language: php
php:
    - 7.1
    - 7.2
    - 7.3

before_install:
    - mysql -e "CREATE DATABASE `mt_test` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;"
    - composer self-update

install:
    - travis_retry composer install --no-progress --prefer-dist

script:
    - vendor/bin/tester tests

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

cache:
    directories:
        - $HOME/.composer/cache